### ISSUE TITLE
mesh: Cannot compile Mesh without cgo

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#112]
We are currently pulling in some part of `go-ethereum` that requires cgo to compile. This is a blocker for browser support so we must investigate and figure out if we can remove the offending dependency.

**Comment by fabioberger** [comment]
According to @opaolini the most likely culprit is the C implementation of secp256k1 that we import from `go-ethereum` to sign orders. In order to resolve this issue, we might need to remove the local signer and use the `eth_sign` call everywhere.

**Comment by opaolini** [comment]
After digging a bit deeper, there exists https://github.com/ethereum/go-ethereum/blob/master/crypto/signature_nocgo.go which ultimately is used when building with the `CGO_ENABLED=0` flag.

Some discussion on fixing the `CGO_ENABLED` flag is here: https://github.com/ethereum/go-ethereum/pull/19121 and on the current master running `CGO_ENABLED=0 go build ...` works.

I haven't been able to successfully compile Mesh without CGO yet, as there are some errors popping up, that could be because of some weird behaviour of vendored in dependencies.

I'll look into it.

**Comment by fabioberger** [comment]
@opaolini that is really promising. I fixed the issue is a hackier way in #127 but would be down to try using `CGO_ENABLED=0` instead. Once `secp256k1` isn't an issue anymore, there is one more hurdle, and thats that `ipc` support in `go-ethereum`'s `rpc` package relies on several cgo methods as well. @albrow we might need to use a fork of the `rpc` package that removes ipc support since we don't use it (unless we want to support it in the near future ofc).
