### ISSUE TITLE
Pros and Cons of Persisting State (Documentation Clarification)

### ISSUE THREAD

**Issue by pointtoken** [0xProject/0x-mesh#344]
The deployment documentation has a brief discussion about state, but leaves many unanswered questions. What are the consequences of not keeping state vs. keeping state? 

If one doesn't persist state, how long does it take for a peer to be current? 

If one does persist state, how smart is the software on being restarted to clean up its state with the current view of the world? 

More explanation of what is happening under the hood in the docs would be great so that people running a node understand the consequences of that decision.

**Comment by fabioberger** [comment]
Thanks for the suggestion @pointtoken. I will add the below to the docs soon. 

If you persist state across re-starts, the Mesh node will be able to literally pick up where it left off after a crash / restart. It'll persist the orders seen and Ethereum blocks processed. Upon restart it'll "fast-sync" the missed Ethereum blocks and process all order-related events. Because of this, it is recommended to persist the Mesh state. If you don't, the node will literally restart as if it is joining the network for the first time, losing all orders found thus far.

We cannot say how long it takes for a peer to be current, since this depends on the number of orders being shared in the network. We do expect there to be a warm-up period for all but the smallest markets however.

**Comment by albrow** [comment]
@pointtoken are you satisfied with this answer and our updated docs? See https://0x-org.gitbook.io/mesh/v/v6.0.1-beta/getting-started/deployment#persisting-state.
