### ISSUE TITLE
Error in browser: "Try Again"

### ISSUE THREAD

**Issue by albrow** [0xProject/0x-mesh#800]
# Context

Augur reported the following issue on Discord:

![](https://cdn.discordapp.com/attachments/518207682470084618/702262898038407229/Screen_Shot_2020-04-21_at_3.png)

Please provide any relevant information about your setup

- Are you running Mesh in the browser or as a standalone server? Are running Mesh inside of Docker or directly running the binary?

In the browser. Chrome on Windows and Mac.

- What version of Mesh are you running? Be as specific as possible (e.g., `8.0.1` instead of `latest` or `8`).

9.2.1 (browser mesh, running with browser mesh lite)
Pending confirmation under 9.3.0

# Expected Behavior

Should not crash.

# Current Behavior

Crashes.

# Failure Information (for bugs)

(See screenshot above)

## Steps to Reproduce

@pgebheim can you answer this? If you don't have exact steps to reproduce, maybe you can describe what were you doing when you saw this error?

## Failure Logs

(See screenshot above)

**Comment by pgebheim** [comment]
## Platform:
Chrome on Windows and Mac.

# Mesh Version
9.2.1 (browser mesh, running with browser mesh lite)

## Suggest priority / severity
Low / Medium

## Description:
This error happens when a browser puts a background tab to sleep. It will stop JavaScript until the tab is resumed.

At this point the wasm will resume, and encounter the fact that it is now too many blocks behind. This will cause a fatal error to propagate go the onError handler.

In response to this fatal error our client code attempts to instantiate a new mesh client, and subsequently call `mesh.startAsync()`. The mesh client begins running, but fails from an irrecoverable LevelDB error. This error will only clear itself up on tab refresh.

## Augurs Solution
In our case we attempt to catch the case where the JavaScript has been out to sleep because our app code needs complete reinitialization to avoid syncing issues. Similar to Mesh, the augur client needs to handle reorgs properly and any inconsistent shutdown requires block rollback to ensure reorgs are handled properly by the streaming sync code.

Because of this -- Augur forces a tab refresh when it encounters this case and thus works around the issue with the leveldb handling.

As such is say this is *low priority* since a complete fix wouldn't result in UX improvement.

**Comment by albrow** [comment]
@pgebheim is this still happening or can we close this issue?
